services:
  - type: web
    name: big5-ah-predictor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app:create_app()'

  - type: cron
    name: refresh-predictions
    runtime: python
    buildCommand: pip install -r requirements.txt
    command: python refresh.py
    schedule: "0 12 * * *"   # daily at 12:00 UTC
